# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            André Noboru
tagline:          'A designer always learning'
description:      'This is the personal blog of André Noboru.'
url:              http://andrenoboru.com
baseurl:          /

author:
  name:           'André Noboru Siraiama'
  url:            https://twitter.com/andrenoboru

paginate:         5

# Custom vars
version:          0.5

github:
  repo:           github.com/andrenoboru/andrenoboru.github.io
